Update sensitivity analysis tutorial
powsybl/powsybl.github.io pull request #144
Opened 2020-09-21 13:14 UTC by TheMaskedTurtle

Changes after sensi API refactoring

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Adapt tutorial to sensi API refactoring

2020-10-02 08:40 UTC, mathbagu requested changes
I think some pages have to be updated:
- the sensitivity analysis API is a now in a new artifact as the module name as changed. It doesn't appear in this diff. We also have to change the artifact.md page.
- grepping to the different pages, we also have to change the sensitivity calculation to sensitivity analysis everywhere?
- I think we also have to update the documentation of the tool.

I think these changes must also be documented in the migration guide.

2020-10-02 08:40 UTC, mathbagu commented on pages/documentation/developer/tutorials/sensitivity-analysis.md
> +        <powsybl.rte-core.version>2.12.0</powsybl.rte-core.version>
We should update the version to the next powsybl version (3.7.0 and 2.14.0), because the new API won't be available in powsybl 3.5.0

2020-10-02 08:40 UTC, mathbagu commented on pages/documentation/developer/tutorials/sensitivity-analysis.md
> +SensitivityAnalysisResults sensiResults = SensitivityAnalysis.find().run(network, factorsProvider);
Remove the extra call to the `find()` method

2020-10-02 08:40 UTC, mathbagu commented on pages/documentation/developer/tutorials/sensitivity-analysis.md
> +Here we directly load the sensitivity analysis parameters from the YML configuration file in the resources.
From the resources or the configuration directory?

2020-10-02 08:40 UTC, mathbagu commented on pages/documentation/developer/tutorials/sensitivity-analysis.md
> +SensitivityAnalysisResults systematicSensiResults = SensitivityAnalysis.find().run(network,
Remove the extra call to the `find()` method, and maybe put all the parameters on a single line if the rendering is OK

2020-10-02 08:43 UTC, mathbagu commented on pages/documentation/developer/tutorials/sensitivity-analysis.md
> +Here we directly load the sensitivity analysis parameters from the YML configuration file in the resources.
Don't take into account this comment: the tutorial is looking for the parameters in the resources :)

2020-10-05 07:00 UTC, murgeyseb requested changes

2020-10-05 10:10 UTC, mathbagu commented on pages/documentation/user/itools/sensitivity-analysis.md
> +    --output-file <FILE>                      sensitivity analysis results
Looking to powsybl-core, there is an `s` to `result`. I can change it, but I need to make a PR in powsybl-core first. @murgeyseb what do you think?

2020-10-05 11:08 UTC, murgeyseb commented on pages/documentation/user/itools/sensitivity-analysis.md
> +    --output-file <FILE>                      sensitivity analysis results
I did not check but that's true... We could keep it like that, it is not so important...

2020-10-05 14:47 UTC, mathbagu approved these changes

2020-10-05 14:53 UTC, murgeyseb approved these changes

2020-10-05 14:56 UTC, merged