Add information about our release cycle
powsybl/powsybl.github.io pull request #257
Opened 2022-04-11 09:34 UTC by miovd

Signed-off-by: VEDELAGO MIORA <miora.ralambotiana@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
No

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Add information about our release cycle

2022-04-11 15:05 UTC, flo-dup requested changes
Great, very clear! just one comment

2022-04-11 15:05 UTC, flo-dup commented on pages/overview/release-cycle.md
> +- its latest version is updated in [powsybl-starter](https://github.com/powsybl/powsybl-starter) and on the [download page](../download/index.md)
Didn't you mean the corresponding repository page? As the download page is only for powsybl-distribution. Which is not referenced here by the way. Should we put it in the release train?

2022-04-12 11:14 UTC, flo-dup approved these changes

2022-04-12 11:21 UTC, geofjamg commented on pages/overview/release-cycle.md
> +- [powsybl-network-area-diagram](https://github.com/powsybl/powsybl-network-area-diagram)
As it is need for releasing pypowsybl, I would add it to base repo to release.

2022-04-20 07:36 UTC, So-Fras approved these changes

2022-04-22 14:36 UTC, merged