Add documentation from groovy tutorial
powsybl/powsybl.github.io pull request #276
Opened 2023-02-06 17:19 UTC by colinepiloquet

Signed-off-by: Coline PILOQUET <coline.piloquet@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [X] The commit message follows our guidelines
- [X] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
No

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Adds documentation about network modifications in Groovy. (same as the readme.md)

2023-03-24 08:58 UTC, So-Fras requested changes
The tutorial is very clear to me and didactic! I only have a few remarks.

2023-03-24 08:58 UTC, So-Fras commented on pages/documentation/developer/tutorials/network_modifications_groovy.md
> +When removing an element, the element itself is removed as well as all the breakers and disconnectors.
I would clarify with "as well as the **associated** breakers and disconnectors".

2023-03-24 08:58 UTC, So-Fras commented on pages/documentation/developer/tutorials/network_modifications_groovy.md
> +The script is adding the load between the transformer TWT (order position 10) and the VSC converter station VSC1 (order position 20). For that, the order position is put to 15 when creating the modif
I would say 
- "the script **adds**..."
- "the order position is **set** to 15 when **adding the load**"

2023-03-24 08:58 UTC, So-Fras commented on pages/documentation/developer/tutorials/network_modifications_groovy.md
> +It is also possible to specify the direction of the load. Here it is not, so by default it is directed to the bottom.
I would say: "It is also possible to specify the direction of the load. **By default,** it is directed to the bottom."

2023-03-24 08:58 UTC, So-Fras commented on pages/documentation/developer/tutorials/network_modifications_groovy.md
> +| BusOrBusbarSectionId1 | /                | The ID of the busbar (node/breaker network) or of the bus (bus/breaker network) on which the branch should be connected on side 1.
Same remark as above, it may be useful to specify that it is a mandatory parameter.

2023-03-24 08:58 UTC, So-Fras commented on pages/documentation/developer/tutorials/network_modifications_groovy.md
> +In this method, the only parameter to give is the id of the connectable that we want to remove. It works for injection as well as branches. In this case, the branch and its topology is removed on bot
I would say 
- "for injection**s**"
- "the branch and its topology **are** removed..."

2023-03-24 08:58 UTC, So-Fras commented on pages/documentation/developer/tutorials/network_modifications_groovy.md
> +The parameters that must be fill is:
"parameter"

2023-03-24 16:27 UTC, colinepiloquet commented on pages/documentation/developer/tutorials/network_modifications_groovy.md
> +| BusOrBusbarSectionId   | /                   | The ID of the busbar (node/breaker network) or of the bus (bus/breaker network) on which the injection should be connected.
I thought that the column Default value was sort of doing this job, but you are right, it might not be very clear. I added a new column

2023-03-30 12:53 UTC, So-Fras approved these changes

2023-04-03 08:15 UTC, merged