Improve CGMES doc
powsybl/powsybl.github.io pull request #287
Opened 2023-04-21 15:04 UTC by miovd

TODO
- detail export

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**
Doc update

2023-04-24 13:25 UTC, So-Fras requested changes
Great documentation work, thank you.
I suggest 2 minor changes.

Is it also possible to take advantage of this PR and modify https://github.com/powsybl/powsybl.github.io/pull/287/files#diff-fd13120da0badc1b6c93c0ceb1e9caf17cc76b9b3e57b9adedf5e257febfadb1R461 in order to remove the reference to powsybl-diagramµ? The CGMES-related code has not been updated for a while in this repo.

2023-04-24 13:25 UTC, So-Fras commented on pages/documentation/grid/formats/cim-cgmes.md
> +
Isn't there a need for details here too ?

```suggestion
<span style="color: red">TODO details</span>
```

2023-04-24 13:25 UTC, So-Fras commented on pages/documentation/grid/formats/cim-cgmes.md
> +If the CGMES `Switch` has its ends in different voltage levels inside the same IGM, it is mapped to a PowSyBl [`Switch`] but the voltage levels, and potentially the substations, that contain its ends
The link towards "switch" is missing.

```suggestion
If the CGMES `Switch` has its ends in different voltage levels inside the same IGM, it is mapped to a [`Switch`](../model/index.md#breakerswitch) but the voltage levels, and potentially the substations, that contain its ends are merged: they are mapped to only one voltage level and/or substation.
```

2023-04-25 09:32 UTC, colinepiloquet commented on pages/documentation/grid/formats/cim-cgmes.md
> +- `TargetP`/`TargetQ` are set from `SSH` or `SV` values depending on which are defined. CGMES values for `p`/`q` are given with load sign convention, so a change in sign is applied when copying them
Typo here: undefined

2023-04-28 11:49 UTC, colinepiloquet approved these changes

2023-05-03 11:51 UTC, So-Fras approved these changes

2023-05-05 12:36 UTC, merged