Improve CGMES documentation regarding transformers and boundaries
powsybl/powsybl.github.io pull request #290
Opened 2023-05-05 14:06 UTC by miovd

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**
Doc update: complete documentation regarding CGMES import of transformers and equipment at boundary

2023-05-09 10:05 UTC, So-Fras requested changes
Thank you again for the documentation work. Most of my remarks are about typos.

2023-05-10 08:40 UTC, colinepiloquet commented on pages/documentation/grid/formats/cim-cgmes.md
> +If the CGMES `Switch`  is mapped to a PowSybl [`DanglingLine`](../model/index.md#dangling-line), its attributes are as described below:
```suggestion
If the CGMES `Switch` is mapped to a PowSyBl [`DanglingLine`](../model/index.md#dangling-line), its attributes are as described below:
```

2023-12-13 16:38 UTC, annetill commented on pages/documentation/grid/formats/cim-cgmes.md
> +- `UcteXnodeCode` is copied from the name of the `TopologicalNode` or the `ConnectivityNode` (respectively in `NODE-BREAKER` or `BUS-BRANCH`) inside boundaries;
Pairing key here.

2024-05-24 14:45 UTC, So-Fras commented
@colinepiloquet I know you have transfered most of the cim-cgmes documentation in readthedocs. What about this PR? Could you check if there is something to get from it and then close it?
Thanks a lot!

2024-05-27 07:00 UTC, annetill commented
> @colinepiloquet I know you have transfered most of the cim-cgmes documentation in readthedocs. What about this PR? Could you check if there is something to get from it and then close it? Thanks a lot!

Indeed I don't like "linking device".

2024-05-30 07:26 UTC, colinepiloquet commented
> > @colinepiloquet I know you have transfered most of the cim-cgmes documentation in readthedocs. What about this PR? Could you check if there is something to get from it and then close it? Thanks a lot!
> 
> Indeed I don't like "linking device".

Me neither. We do need to integrate this PR in the documentation though. I have trouble finding another word for linking device.

2024-06-03 12:59 UTC, colinepiloquet commented
I have done some corrections, according to your feedback @So-Fras and @annetill. Once merged, I will transfer it to the documentation on readthedocs.

2024-06-03 13:34 UTC, So-Fras requested changes

2024-06-03 13:34 UTC, So-Fras commented on pages/documentation/grid/formats/cim-cgmes.md
> +- `ParingKey` is copied from the name of the `TopologicalNode` or the `ConnectivityNode` (respectively in `NODE-BREAKER` or `BUS-BRANCH`) inside boundaries
Small typo: "Pairing"

2024-06-04 15:31 UTC, So-Fras approved these changes

2024-06-04 15:35 UTC, merged