[Shortcircuit] Add documentation about new parameters
powsybl/powsybl.github.io pull request #296
Opened 2023-09-20 08:24 UTC by colinepiloquet

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**
Docs update

**What is the new behavior (if this is a feature change)?**
New parameters were added to the API. This PR is to document them.

2024-02-07 15:25 UTC, colinepiloquet commented
@annetill, @So-Fras, if one of you would have time to review this addition to the documentation it would be great.
It's about the new parameters that were added (some time ago) for the short circuit analyses.
Many thanks

2024-02-22 13:00 UTC, annetill commented on pages/documentation/simulation/shortcircuitanalysis/index.md
> +The short-circuit API allows the calculation of currents and voltages on a network after a fault.
You call that an implementation, available in powsybl-incubator.

2024-02-22 14:51 UTC, So-Fras requested changes
Just a minor comment. Great documentation work!

2024-02-22 14:51 UTC, So-Fras commented on pages/documentation/simulation/shortcircuitanalysis/index.md
> +- `PREVIOUS`: the voltage profile from the loadflow will is for the calculation
```suggestion
- `PREVIOUS`: the voltage profile from the loadflow is used for the calculation
```

2024-02-26 10:17 UTC, So-Fras approved these changes

2024-02-26 10:21 UTC, annetill commented on pages/documentation/simulation/shortcircuitanalysis/index.md
> +This property allows to define an optional coefficient, in case of a subtransient study, to apply to the transient reactance of generators to get the subtransient one:
Same with subtransient one.

2024-02-26 10:22 UTC, annetill commented on pages/documentation/simulation/shortcircuitanalysis/index.md
> +Only the nodes where the voltage drop due to the short circuit is above this property are kept.
The drop in absolute value.

2024-02-26 10:27 UTC, annetill commented on pages/documentation/simulation/shortcircuitanalysis/index.md
> +- `PREVIOUS`: the voltage profile from the loadflow is used for the calculation
load flow

2024-02-26 10:27 UTC, annetill commented on pages/documentation/simulation/shortcircuitanalysis/index.md
> +In the case of CONFIGURED voltage profile, ranges of nominal voltages with multiplicative coefficients must be specified in the `voltage-ranges` property.
`CONFIGURED`

2024-02-26 10:30 UTC, colinepiloquet commented on pages/documentation/simulation/shortcircuitanalysis/index.md
> +This property allows to define an optional coefficient, in case of a subtransient study, to apply to the transient reactance of generators to get the subtransient one:
sub-transient, you are right

2024-02-26 10:39 UTC, annetill approved these changes

2024-02-26 11:28 UTC, merged