Update tutorials documentation
powsybl/powsybl.github.io pull request #299
Opened 2023-10-16 13:49 UTC by colinepiloquet

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

No

**What kind of change does this PR introduce?**

Docs

**What is the current behavior?**

Documentation is based on previous versions of PowSyBl and of the tutorials

**What is the new behavior (if this is a feature change)?**
Update the doc.

2023-11-06 08:33 UTC, annetill approved these changes

2023-11-06 08:36 UTC, annetill requested changes
Indeed the export is wrong, the context is not exported anymore.

2023-11-07 09:00 UTC, colinepiloquet commented
> Indeed the export is wrong, the context is not exported anymore.

I changed it. Actually I also add some changes in the loadflow tutorial documentation that I did not commit yet.

2023-12-01 17:12 UTC, annetill approved these changes

2023-12-01 17:12 UTC, merged