Update network and extension documentation
powsybl/powsybl.github.io pull request #303
Opened 2023-12-13 09:07 UTC by annetill

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2023-12-13 09:57 UTC, So-Fras requested changes
Thank you for updating the documentation, I think it is clearer this way (especially the removal of the "branches" paragraph in index.md). I left comments / suggestions for small typos. Hope it helps!

2023-12-13 09:57 UTC, So-Fras commented on pages/documentation/grid/formats/cim-cgmes.md
> +CIM-CGMES format contains more information that what the `iidm` grid model need for calculation. The additional data, that are needed to export a network in CIM-CGMES format, are stored in several ex
... tha**n** what the `iidm` grid model need**s** for calculation.

2023-12-13 09:57 UTC, So-Fras commented on pages/documentation/grid/model/extensions.md
What about we keep a paragraph on this page named something like "CIM-CGMES extensions" that will only redirect into the cim-cgmes.md "extensions" paragraph? 

It would give the user another option to find their way (after all a cim-cgmes extension is still an extension :D)

2023-12-13 09:57 UTC, So-Fras commented on pages/documentation/grid/model/index.md
> +Almost all elements modeled in the network are identified through a unique `id`, and optionally described by a `name` that is easier to interpret for a human. Almost all components can be [extended](
Almost all **the** elements...

2023-12-13 09:57 UTC, So-Fras commented on pages/documentation/grid/model/index.md
> +The validation level can be `EQUIPMENT` or `STEADY_STATE_HYPOTHESIS`. A network at equipment level is a network with missing steady-state hypothesis. This occurs just after SCADA systems, before any
1. "A network at equipment level is a network with missing steady-state hypothesis"
- If there are several steady-state hypotheses, then it's "hypothes**e**s" (the plural is irregular)
- Id there is only one hypothesis, then it's "with **a** missing steady-state hypothesis"

2. "Once, all steady-state hypothes**e**s... perfom a computation, the **validation** level..."

2023-12-13 09:57 UTC, So-Fras commented on pages/documentation/grid/model/index.md
> +A generator is an equipment that injects or consumes active power, and injects or consumes reactive power. It may be controller to hold a voltage or reactive target somewhere in the network, not nece
"It may be **used as a controller** to hold..."

2023-12-13 09:57 UTC, So-Fras commented on pages/documentation/grid/model/index.md
> +In case the line is a boundary, a pairing key $$pairingKey$$ (in previous network versions $$UcteXnodeCode$$) is defined besides the characteristics of the Table. It is a key to match two dangling li
Is the upper case necessary for **T**able?

2023-12-13 09:57 UTC, So-Fras commented on pages/documentation/grid/model/index.md
> +The equations of the a line, in complex notations, are as follow:
I don't get what "the **a** line" means.

2023-12-13 10:42 UTC, So-Fras approved these changes

2024-01-26 13:59 UTC, annetill commented on pages/documentation/grid/formats/cim-cgmes.md
> +| ID                               | String     | -    | yes      | -             | The IF of the control area                               |
IF or ID?

2024-01-29 13:00 UTC, jeandemanged requested changes
just listing some pending topics from colleagues and myself

2024-01-29 13:00 UTC, jeandemanged commented on pages/documentation/grid/model/index.md
@p-arvy please add RTC reactive power control from https://github.com/powsybl/powsybl-core/pull/2758

2024-01-31 13:21 UTC, jeandemanged approved these changes
great job everyone :)

2024-01-31 13:25 UTC, merged