[WIP] Update to 2024.0.0 release train
powsybl/powsybl.github.io pull request #304
Opened 2024-02-01 09:58 UTC by olperr1

**Please check if the PR fulfills these requirements**

- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

Update website to 2024.0.0 release train

2024-02-15 13:09 UTC, So-Fras approved these changes
Thank you for this work. I would like to add another commit to take into account the 1.3.0 pypowsybl version that is about to be released before merging!

2024-02-20 08:08 UTC, pet-mit requested changes

2024-02-20 08:08 UTC, pet-mit commented on pages/documentation/developer/repositories/index.md
> +**Committers:** [pet-mit](https://github.com/pet-mit), [phiedw](https://github.com/phiedw)
```suggestion
**Reviewers:** [bqth29](https://github.com/bqth29), [benrejebmoh](https://github.com/benrejebmoh), [Godelaine](https://github.com/Godelaine), [jipea](https://github.com/jipea), [MartinBelthle](https://github.com/MartinBelthle), [murgeyseb](https://github.com/murgeyseb), [pet-mit](https://github.com/pet-mit), [phiedw](https://github.com/phiedw)
**Committers:** [bqth29](https://github.com/bqth29), [benrejebmoh](https://github.com/benrejebmoh), [Godelaine](https://github.com/Godelaine), [jipea](https://github.com/jipea), [MartinBelthle](https://github.com/MartinBelthle), [murgeyseb](https://github.com/murgeyseb), [pet-mit](https://github.com/pet-mit), [phiedw](https://github.com/phiedw)
```

2024-02-20 17:42 UTC, pet-mit approved these changes

2024-02-20 17:44 UTC, merged